### ISSUE TITLE
black screen with cursor after install

### ISSUE THREAD

**Issue by XoniBlue** [MMM-CalendarExt2/MMM-CalendarExt2#102]
here are the pm2 logs 

`/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:6:14)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:786:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:645:32) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js',
0|mm       |     '/home/pi/MagicMirror/js/app.js',
0|mm       |     '/home/pi/MagicMirror/js/electron.js',
0|mm       |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
`

just gives black screen

**Comment by XoniBlue** [comment]
did rm -rf and redid install process.. all is working
