### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Not supported when trying to run in screen on boot

### ISSUE THREAD

**Issue by pomtom44** [MMM-CalendarExt2/MMM-CalendarExt2#166]
Im not 100% sure if your able to help with this, but it only happens with this module so posting here for help

I have a server which runs a few different MM instances (each runs in a screen session which is generated on boot)
I did a big upgrade of my install, fresh install of MM, fresh install of the modules etc, but now im getting an error when it tries to load the calendar module

```bash
[08.03.2022 10:51.46.627] [ERROR] (node:5927) UnhandledPromiseRejectionWarning: Error: Not supported
    at fetch (/home/administrator/OfficeL/modules/MMM-CalendarExt2/node_helper.js:6:24)
    at Class.scanCalendar (/home/administrator/OfficeL/modules/MMM-CalendarExt2/node_helper.js:91:28)
    at Class.startScanCalendars (/home/administrator/OfficeL/modules/MMM-CalendarExt2/node_helper.js:40:12)
    at Class.work (/home/administrator/OfficeL/modules/MMM-CalendarExt2/node_helper.js:35:10)
    at Class.socketNotificationReceived (/home/administrator/OfficeL/modules/MMM-CalendarExt2/node_helper.js:24:14)
    at Socket.socket.on (/home/administrator/OfficeL/js/node_helper.js:109:11)
    at Socket.emit (events.js:198:13)
    at Socket.emitUntyped (/home/administrator/OfficeL/node_modules/socket.io/dist/typed-events.js:69:22)
    at process.nextTick (/home/administrator/OfficeL/node_modules/socket.io/dist/socket.js:466:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[08.03.2022 10:51.46.628] [ERROR] (node:5927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 23)
[08.03.2022 10:51.46.629] [ERROR] (node:5927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Repeats over and over for each calendar I have set to download

The odd thing is, it only happens when I use my startup script

if I run the server normally, it works fine
if I create a screen session manually, it works fine
if I run the startup script manually, it works fine

Its only when I reboot the server and the script runs on startup where I have this error

**Comment by klaernie** [comment]
That sounds to me like you have two versions of nodes installed, and one of them is unavailable during the early boot phases, where your screen setup starts (like maybe only exists inside an encrypted `/home` mount).

Maybe preface your startup script with something like `which nodejs` to see which binary is used, then do the same for your session. 
My biggest suspect would be, that your OS brings an  ancient version of nodejs that is below our minimum version, and you have a newer version installed just for you.

**Comment by clla1972** [comment]
> That sounds to me like you have two versions of nodes installed, and one of them is unavailable during the early boot phases, where your screen setup starts (like maybe only exists inside an encrypted `/home` mount).
> 
> Maybe preface your startup script with something like `which nodejs` to see which binary is used, then do the same for your session. My biggest suspect would be, that your OS brings an ancient version of nodejs that is below our minimum version, and you have a newer version installed just for you.

Hi! I am having the same problem. I am a newby here so what would be the specific steps to do to solve the problem? How do I check if I have 2 versions of nodes installed?    THANKS !!!!!

**Comment by klaernie** [comment]
@clla1972 If you're not working on a huge system with petabytes of filled storage connected a `find / -type f -name node` should find you all files called `node`, if you've give it an hour to search your entire system.

**Comment by pillbug22** [comment]
Similar error

```
[05.10.2022 17:25.53.458] [ERROR] (node:2697) UnhandledPromiseRejectionWarning: Error: Not supported
    at fetch (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:3:24)
    at Class.scanCalendar (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:89:28)
    at Class.startScanCalendars (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:38:12)
    at Class.work (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:33:10)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:22:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:108:11)
    at Socket.emit (events.js:200:13)
    at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:475:39
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

in the console and no Calendar module appearing on the MM after just updating a MM system (raspberry apt update, git updates for MM itself and all extra modules, including MMM-Calendar).


```
pi@SD-GarageMirror:~ $ nvm current
v18.10.0
pi@SD-GarageMirror:~ $
pi@SD-GarageMirror:~ $
pi@SD-GarageMirror:~ $ nvm ls
->     v18.10.0
         system
default -> stable (-> v18.10.0)
node -> stable (-> v18.10.0) (default)
stable -> 18.10 (-> v18.10.0) (default)
iojs -> N/A (default)
lts/* -> lts/gallium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.20.1 (-> N/A)
lts/gallium -> v16.17.1 (-> N/A)
pi@SD-GarageMirror:~ $
pi@SD-GarageMirror:~ $
pi@SD-GarageMirror:~ $ nvm install stable
v18.10.0 is already installed.
Now using node v18.10.0 (npm v8.19.2)
pi@SD-GarageMirror:~ $ 

```

**Comment by klaernie** [comment]
@pillbug22 : you did run npm install for each module after pulling the updates from git, right? (just making sure)

**Comment by pillbug22** [comment]
@klaernie Correct. I'm always up for new suggestions, but here's what I have been using to update/reset when doing updates. I'll do this for the main MM, then again inside each module subdirectory to get them updated to "default", then I'll add back any customizations like CSS changes.

```
git fetch
git reset --hard HEAD
git merge '@{u}'
git pull && npm install --only=prod --omit=dev
```

This morning I had one of the other modules notifying there was another update available, so I went ahead and did an update on the main MM and also all my modules. Both the main MM and the CalendarExt2 both said already up to date. However, I'm not seeing the above error of "UnhandledPromiseRejectionWarning" in the console any more.

It's still not showing the calendar, but the above error related to this issue seems to be resolved.
`[LOG]   [CALEXT2] calendar:Daily Workout >> Scanned: 0, Selected: 0`
